import './globals.css'
import TanstackProvider from './providers/TanstackProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanstackProvider>
          {children}
        </TanstackProvider>
      </body>
    </html>
  )
}
